### ISSUE TITLE
Build issues on api 27

### ISSUE THREAD

**Issue by emanuelet** [WellingtonCosta/convalida#15]
First the project compiles with the following dependencies.
```gradle
compile 'com.github.WellingtonCosta:convalida:1.3.4'
annotationProcessor 'com.github.WellingtonCosta.convalida:convalida-compiler:1.3.4'
```
Second of all, when I try to run the project I get the errors:
```
Error:java.lang.IllegalAccessException: no such method: convalida.compiler.ConvalidaProcessor.lambda$parseValidateOnClick$0(Element)boolean/invokeStatic
Error:java.lang.NoClassDefFoundError: com/sun/tools/javac/tree/JCTree$Visitor
Error:java.lang.ClassNotFoundException: Class com.sun.tools.javac.tree.JCTree$Visitor not found
```

**Comment by emanuelet** [comment]
I want also to point out that in my project I don't have Kotlin

**Comment by WellingtonCosta** [comment]
The Travis CI build has been failed. I'm working on it...

**Comment by WellingtonCosta** [comment]
Good news!

I fixed the build problem. The build error is due some mistake between Travis CI and Android 27 ([more details here](https://github.com/travis-ci/travis-ci/issues/8874)).

I'm releasing a new version...

**Comment by WellingtonCosta** [comment]
Try it now:

```groovy
compile 'com.github.WellingtonCosta:convalida:1.3.5'
annotationProcessor 'com.github.WellingtonCosta.convalida:convalida-compiler:1.3.5'
```

**Comment by emanuelet** [comment]
It now comes up with the error:
```
Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.WellingtonCosta:convalida-annotations:1.3.5.
```
I saw in the commit where you converted the code from Kotlin to Java that you removed these lines from the `build.gradle` of **convalida-annotations** and **convalida-compiler**
```groovy
-apply plugin: 'maven'	
-group = 'com.github.WellingtonCosta'
```
I have to assume that those were responsible for packaging the dependency with the rest.

**Comment by WellingtonCosta** [comment]
Hi, @emanuelet 

I fixed a lot of issues and released a new version. Please, try it.

```groovy
compile 'com.github.WellingtonCosta:convalida:1.3.6'
annotationProcessor 'com.github.WellingtonCosta.convalida:convalida-compiler:1.3.6'
```

Just, thanks for the help!

**Comment by emanuelet** [comment]
I'm still getting the same error that I got with **1.3.4**.
If I have to interpret the error it appears that is not able to use the lambda inside the `parseValidateOnClick` at [this line](https://github.com/WellingtonCosta/convalida/blob/ccca762799585203969e855c9307a74b2104aa42/convalida-compiler/src/main/java/convalida/compiler/ConvalidaProcessor.java#L259).

Could it maybe be an incompatibility with Java 8?

**Comment by WellingtonCosta** [comment]
What is your Java version?

**Comment by emanuelet** [comment]
In theory I'm using Java 8 as well.

I have this in my build.gradle
```groovy
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by WellingtonCosta** [comment]
This is very stranger... In the __sample__ module I used the same ```compileOptions``` and it works fine.

**Comment by emanuelet** [comment]
I tried multiple things but nothing worked so far. Googling the error didn't reveal much information about possible causes

**Comment by WellingtonCosta** [comment]
Ok... I will rewrite Java 8 code to Java 7 code to avoid these incompatibilities, right?

**Comment by emanuelet** [comment]
I guess that could be the thing. I looked at Butterknife and they're still at Java 7 as well

**Comment by WellingtonCosta** [comment]
I also think this...

I'm releasing a development release for test...

**Comment by WellingtonCosta** [comment]
Ok, try it now:

```groovy
implementation 'com.github.WellingtonCosta.convalida:convalida:development-SNAPSHOT'
annotationProcessor 'com.github.WellingtonCosta.convalida:convalida-compiler:development-SNAPSHOT'
```

**Comment by emanuelet** [comment]
Yeah this works

**Comment by WellingtonCosta** [comment]
Nice! I will release the 1.3.7 version. Thank you for the help! :)

**Comment by WellingtonCosta** [comment]
Done!

```groovy
implementation 'com.github.WellingtonCosta.convalida:convalida:1.3.7'
annotationProcessor 'com.github.WellingtonCosta.convalida:convalida-compiler:1.3.7'
```
